### PR TITLE
iOS support

### PR DESCRIPTION
**Pull request by MrUnfunny**
Hey @i5hi,
I have made some changes for iOS support. Most things seem to work fine. However there are some issues which we can fix in this PR itself.

1. '.a' files generated by stackmate-core doesn't seem to work with emulator on m1. For this, we either have to run Xcode using rosetta or generate .a file with target set to ```aarch64-apple-ios-sim```.
2. ```dummyMethodToEnforceBundling``` in swift file seems to have ```derive_hardened``` and ```days_to_blocks``` methods but can't find the same in stackmate-core. So, it throws an error. I've commented these for now.
3. Tor package not working. So, we might have to disable it for iOS.
4. There was some file size issue while pushing to Github. So, I've removed it for now. We can add it using ```update-core.sh```.

### CODE REVIEW

**Comment by i5hi** [comment]
Hey, thanks. Will review this tomorrow.

**Comment by i5hi** [comment]
Hey! Sorry it took me a while. 

Few notes in reference the points you made:

1. stackmate-core needs to figure out compiling ios binaries

This is the main dependency.

Working on it here:

https://github.com/StackmateNetwork/stackmate-core/issues/15

We need a complete solution as a bash script. For android binaries `scripts/init.sh` and `scripts/build.sh`.

The goal is to make the build process simple so anyone can build it themselves. Its far from there at the moment but its getting there.

IOS builds are generally easier on apple devices and apple users most likely have those devices. So it makes sense to write the script for that first. I've attempted ios on linux a few times and was never able to get it working within the time I had.  Now trying it on an m1 and i think that should be easier. All the xcode tools can be installed with brew and then its mostly some cargo commands and making sure paths are all set correctly for all the libraries required. 

If you are attempting cross-compilation please add any documentation in the `docs` folder, that will help a lot. 

The Andoird build manual process is documented there as `build01.md` 
https://github.com/StackmateNetwork/stackmate-core/blob/main/docs/build01.md. 

Its a good starting point because it explains more details of the process of cross compilation.

2. Not sure about swift, will have to look a bit more into this.

3. Yes. Tor is default on stackmate. Earlier it was enforced to run the Tor daemon within the app. Now you can chose to run an external tor app like Orbot and only enter the socks5 port in the stackmate app (default is 9050) - so you don't have to run the daemon from within the app. This allows us to work around ios support. IOS users wont get Tor daemon, they will have to run tor externally via orbot to use the app.

4. We will have to monitor all the build artifacts being created in this process and manually add them into .gitignore

**Comment by MrUnfunny** [comment]
Hey @i5hi, tried creating iOS build from Linux but cannot get it to work. It works fine on Mac though. I will add build instructions for mac in https://github.com/StackmateNetwork/stackmate-core/blob/main/docs/build01.md. Also, should we upload prebuilt binaries for stackmate-core instead of building it on the user's machine?

**Comment by i5hi** [comment]
> Hey @i5hi, tried creating iOS build from Linux but cannot get it to work. It works fine on Mac though. I will add build instructions for mac in https://github.com/StackmateNetwork/stackmate-core/blob/main/docs/build01.md. Also, should we upload prebuilt binaries for stackmate-core instead of building it on the user's machine?

Yeah. Its hard on Linux. Mac builds are a good enough to start.

Please do add instructions and I will try it out. Yes, we upload prebuilt binaries as releases. If your instructions work for me we will add them to the next release.

**Comment by i5hi** [comment]
Hey! So, we are going to be porting the entire bitcoin ops in the-stackmate to use bdk-flutter instead of stackmate-core.

bdk-flutter seems to be pretty stable now and has also made it to pub.dev

It is missing some functionality that we would like to have like batch txs, support for script with policy id and coin selection but these should be upgrades that we can make by contributing to it. 

Closing this issue since we are going to consider stackmate-core deprecated from now.

**Comment by MrUnfunny** [comment]
That's good news. bdk-flutter is getting pretty stable. the-stackmate will be a good reference for others who want to use the package.

**Pull request closed without merging**
